version: '3'
services:
  gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM
      - XAUTHORITY
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.Xauthority:/tmp/.Xauthority:rw
    command: ign gazebo --headless-rendering
    network_mode: "host"
    privileged: true